"""Storage adapter: Cloudinary when CLOUDINARY_URL is set, otherwise local disk served at /media."""
import io
import logging
import re
import uuid
from pathlib import Path
from urllib.parse import unquote, urlparse

import cloudinary
import cloudinary.uploader

from app.config import get_settings

log = logging.getLogger("hod.storage")

UPLOAD_DIR = Path(__file__).resolve().parent.parent.parent / "uploads"
LOCAL_PREFIX = "local:"
_EXT = {"image/jpeg": "jpg", "image/png": "png", "image/webp": "webp"}


def _cloudinary_configured() -> bool:
    url = get_settings().cloudinary_url.strip()
    if not url.startswith("cloudinary://"):
        return False
    p = urlparse(url)
    if not (p.username and p.password and p.hostname):
        return False
    cloudinary.config(
        cloud_name=p.hostname,
        api_key=unquote(p.username),
        api_secret=unquote(p.password),
        secure=True,
    )
    return True


def storage_mode() -> str:
    return "cloudinary" if _cloudinary_configured() else "local"


def upload(data: bytes, content_type: str, folder: str) -> tuple[str, str]:
    """Store an image. Returns (url, public_id). Raises on provider failure."""
    if _cloudinary_configured():
        res = cloudinary.uploader.upload(io.BytesIO(data), folder=f"hod/{folder}", resource_type="image")
        return res["secure_url"], res["public_id"]

    name = f"{uuid.uuid4().hex}.{_EXT[content_type]}"
    target_dir = UPLOAD_DIR / folder
    target_dir.mkdir(parents=True, exist_ok=True)
    (target_dir / name).write_bytes(data)
    base = get_settings().backend_public_url.rstrip("/")
    return f"{base}/media/{folder}/{name}", f"{LOCAL_PREFIX}{folder}/{name}"


def delete(public_id: str | None) -> None:
    """Best effort: never raises. Cloudinary and local assets are told apart by the id prefix."""
    if not public_id:
        return
    try:
        if public_id.startswith(LOCAL_PREFIX):
            rel = public_id[len(LOCAL_PREFIX):]
            # ids are generated by us, but never follow anything outside the upload dir
            if re.fullmatch(r"[a-z]+/[0-9a-f]{32}\.(jpg|png|webp)", rel):
                (UPLOAD_DIR / rel).unlink(missing_ok=True)
        elif _cloudinary_configured():
            cloudinary.uploader.destroy(public_id, resource_type="image")
    except Exception:
        log.warning("Could not delete old asset %s", public_id, exc_info=True)
