"""stage1 tables

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 09:56:34.845840
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopkeepers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address_text', sa.Text(), nullable=True),
    sa.Column('lat', sa.Double(), nullable=True),
    sa.Column('lng', sa.Double(), nullable=True),
    sa.Column('delivery_radius_km', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('photo_public_id', sa.Text(), nullable=True),
    sa.Column('upi_vpa', sa.String(length=120), nullable=True),
    sa.Column('min_order_value', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('is_open', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['shopkeepers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('sell_mode', sa.Enum('pack', 'loose', name='sell_mode'), nullable=False),
    sa.Column('pack_size', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('pack_unit', sa.Enum('g', 'kg', 'ml', 'l', 'pc', 'dozen', 'packet', name='pack_unit'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_qty', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=10, scale=3), server_default='5', nullable=False),
    sa.Column('max_normal_qty', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('shelf', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_shop_active', 'products', ['shop_id', 'is_active'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('shop_photo', 'list_image', 'audio', name='upload_kind'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('public_id', sa.Text(), nullable=True),
    sa.Column('mime', sa.String(length=80), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('new_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    op.drop_table('uploads')
    op.drop_index('ix_products_shop_active', table_name='products')
    op.drop_table('products')
    op.drop_table('shops')
    op.drop_table('shopkeepers')
    # ### end Alembic commands ###
