"use client";

import { useCallback, useEffect, useState } from "react";
import { MockBadge } from "@/components/ui/MockBadge";
import { Spinner } from "@/components/ui/Spinner";
import { api, ApiError } from "@/lib/api";
import { maskPhone } from "@/lib/format";
import type { DemoInbox as Inbox } from "@/lib/types";

/** Mock mode only: shows the "SMS" the backend would have sent. Polls every 3 seconds while open. */
export function DemoInbox({ phone, onClose }: { phone: string; onClose: () => void }) {
  const [data, setData] = useState<Inbox | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [now, setNow] = useState(() => Date.now());

  const poll = useCallback(async () => {
    try {
      setData(await api<Inbox>(`/auth/customer/otp/demo-inbox?phone=${encodeURIComponent(phone)}`));
      setError(null);
    } catch (e) {
      setError(e instanceof ApiError ? e.message : "Could not load the demo inbox.");
    }
  }, [phone]);

  useEffect(() => {
    poll();
    const t = setInterval(poll, 3000);
    const clock = setInterval(() => setNow(Date.now()), 1000);
    return () => {
      clearInterval(t);
      clearInterval(clock);
    };
  }, [poll]);

  const msg = data?.messages[0];
  const secsLeft = msg ? Math.max(0, Math.round((new Date(msg.expires_at).getTime() - now) / 1000)) : 0;

  return (
    <aside
      aria-label="Demo SMS inbox"
      className="fixed bottom-4 right-4 top-4 z-50 flex w-[min(360px,calc(100vw-2rem))] flex-col gap-4 rounded-card border-[3px] border-ink bg-cream-yellow p-5 shadow-brutal"
    >
      <div className="flex items-center justify-between gap-2">
        <div>
          <p className="eyebrow">Demo SMS inbox</p>
          <h3 className="text-xl">{maskPhone(phone)}</h3>
        </div>
        <button type="button" onClick={onClose} aria-label="Close inbox" className="btn-secondary !px-3 !py-1">
          ✕
        </button>
      </div>
      <MockBadge>MOCK SMS</MockBadge>
      <p className="text-sm text-muted">
        No real SMS is sent in demo mode. The code below is random and generated by the server, exactly as a real SMS
        would carry it.
      </p>

      {!data && !error ? (
        <Spinner label="Checking for messages…" />
      ) : error ? (
        <div role="alert" className="rounded-input bg-danger-fill p-3 text-sm text-danger">
          {error} Retrying…
        </div>
      ) : msg ? (
        <div className="rounded-input bg-white p-4 shadow-clay">
          <p className="text-sm text-muted">From: HODESK</p>
          <p className="mt-1">Your Hinglish Order Desk code is</p>
          <p className="my-2 font-mono text-3xl font-bold tracking-[0.3em]" data-testid="demo-otp-code">
            {msg.code}
          </p>
          <p className="text-sm text-muted">
            {secsLeft > 0 ? `Expires in ${Math.floor(secsLeft / 60)}:${String(secsLeft % 60).padStart(2, "0")}` : "Expired"}
          </p>
        </div>
      ) : (
        <div className="rounded-input bg-white p-4 text-center text-muted shadow-clay">
          No active code. Request one in the verify window.
        </div>
      )}
    </aside>
  );
}
